### ISSUE TITLE
单例模式更优化的实现方法

### ISSUE THREAD

**Issue by zenuo** [chenjazz/AntSubject#1]
https://github.com/chenjazz/AntSubject/blob/d7889b174fac739e844968798dd0aa6c97e0f814/src/main/java/Singleton.java#L7

此处可用`枚举`来实现单例模式，参考Effective Java的[Item 3: Enforce the singleton property with a private constructor or an enum type](http://www.informit.com/articles/article.aspx?p=1216151&seqNum=3)

**Comment by chenjazz** [comment]
@zenuo 题目明确要求使用懒汉式--

**Comment by zenuo** [comment]
好的- -

陈佳志 <notifications@github.com>于2018年7月14日 周六下午12:11写道：

**Comment by chenjazz** [comment]
@zenuo README.md中

**Comment by zenuo** [comment]
原来如此，AntSubject是一个题目的repo吗_(:з」∠)_

**Comment by chenjazz** [comment]
是的

**Comment by zenuo** [comment]
(ゝ∀･)好的
